patchesStrategicMerge:
- database-connection-sealed-secret.yaml
- database-migration-connection-sealed-secret.yaml
- mapping.yaml
- deployment.yaml
- aws-key-sealed-secret.yaml
images:
- name: greenstand/treetracker-earnings-api
  newTag: 1.18.9
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
